-- MySQL Script generated by MySQL Workbench
-- Thu Sep 13 23:58:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `idCiudad` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idProvincia` INT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_Ciudad_Provincia1_idx` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_Provincia1`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `mydb`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coche` (
  `idCoche` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(6) NULL,
  `modelo` VARCHAR(20) NULL,
  `marca` VARCHAR(20) NULL,
  `color` VARCHAR(30) NULL,
  `estado` VARCHAR(30) NULL,
  `kilometraje` INT NULL,
  `idConcesionario` INT NULL,
  PRIMARY KEY (`idCoche`),
  INDEX `fk_Coche_Concesionario_idx` (`idConcesionario` ASC) VISIBLE,
  CONSTRAINT `fk_Coche_Concesionario`
    FOREIGN KEY (`idConcesionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` INT NOT NULL,
  `idCliente` INT NULL,
  `idConsecionario` INT NULL,
  `monto` INT NULL,
  `fechaHora` DATETIME NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_Concesionario1_idx` (`idConsecionario` ASC) VISIBLE,
  INDEX `fk_Compra_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Concesionario1`
    FOREIGN KEY (`idConsecionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concesionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Concesionario` (
  `idConcesionario` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `idUbicacion` INT NULL,
  `idTaller` INT NULL,
  PRIMARY KEY (`idConcesionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDireccion` INT NOT NULL,
  `zipCode` INT NOT NULL,
  `idCiudad` INT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_Direccion_Ciudad1_idx` (`idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Ciudad1`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `mydb`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `idConcesionario` INT NULL,
  `idTaller` INT NULL,
  `FechaContratacion` DATE NULL,
  `Salario` INT NULL,
  PRIMARY KEY (`idMecanico`),
  INDEX `fk_Mecanico_Persona1_idx` (`idPersona` ASC) VISIBLE,
  INDEX `fk_Mecanico_Concesionario1_idx` (`idConcesionario` ASC) VISIBLE,
  INDEX `fk_Mecanico_Taller1_idx` (`idTaller` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_Concesionario1`
    FOREIGN KEY (`idConcesionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_Taller1`
    FOREIGN KEY (`idTaller`)
    REFERENCES `mydb`.`Taller` (`idTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `idPais` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(40) NULL,
  `apellidos` VARCHAR(40) NULL,
  `telefono` INT NULL,
  `extension` INT NULL,
  `idUbicacion` INT NULL,
  PRIMARY KEY (`idPersona`, `cedula`),
  INDEX `fk_Persona_Ubicacion1_idx` (`idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Ubicacion1`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `mydb`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idPais` INT NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `name_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Provincia_Pais1_idx` (`idPais` ASC) VISIBLE,
  CONSTRAINT `fk_Provincia_Pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `mydb`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reparacion` (
  `idReparacion` INT NOT NULL,
  ` idMecanico` INT NULL,
  `idCoche` INT NULL,
  `fechaHoraInicio` DATETIME NULL,
  `fechaHoraFinal` DATETIME NULL,
  PRIMARY KEY (`idReparacion`),
  INDEX `fk_Reparacion_Mecanico1_idx` (` idMecanico` ASC) VISIBLE,
  INDEX `fk_Reparacion_Coche1_idx` (`idCoche` ASC) VISIBLE,
  CONSTRAINT `fk_Reparacion_Mecanico1`
    FOREIGN KEY (` idMecanico`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparacion_Coche1`
    FOREIGN KEY (`idCoche`)
    REFERENCES `mydb`.`Coche` (`idCoche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Taller` (
  `idTaller` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `idUbicacion` INT NULL,
  PRIMARY KEY (`idTaller`),
  INDEX `fk_Taller_Ubicacion1_idx` (`idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Taller_Ubicacion1`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `mydb`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ubicacion` (
  `idUbicacion` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `idDireccion` INT NULL,
  PRIMARY KEY (`idUbicacion`),
  INDEX `fk_Ubicacion_Direccion1_idx` (`idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Ubicacion_Direccion1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
