-- MySQL Script generated by MySQL Workbench
-- Thu Sep 13 21:22:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coche` (
  `idCoche` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(6) NULL,
  `modelo` VARCHAR(20) NULL,
  `marca` VARCHAR(20) NULL,
  `color` VARCHAR(30) NULL,
  `estado` VARCHAR(30) NULL,
  `kilometraje` INT NULL,
  `idConcesionario` INT NULL,
  PRIMARY KEY (`idCoche`),
  INDEX `fk_Coche_Concesionario_idx` (`idConcesionario` ASC) VISIBLE,
  CONSTRAINT `fk_Coche_Concesionario`
    FOREIGN KEY (`idConcesionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concesionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Concesionario` (
  `idConcesionario` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `idUbicacion` INT NULL,
  `idTaller` INT NULL,
  PRIMARY KEY (`idConcesionario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
