USE [master]
RESTORE DATABASE [BASESTECBAK] 
FROM  DISK = N'D:\openfolder\backups\BASESTEC.bak' WITH  FILE = 1,  
MOVE N'BASESTEC' TO N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\BASESTECBAK.mdf',  
MOVE N'BASESTEC_log' TO N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\BASESTECBAK_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5, NORECOVERY

GO


