INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(3,391)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(3,181)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(3,314)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(3,174)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(3,244)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(4,179)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(4,402)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(4,419)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(4,89)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(4,142)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(6,414)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(6,217)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(7,257)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(8,34)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(8,169)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(8,130)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(14,418)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(14,340)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(14,33)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(14,25)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(16,205)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(16,4)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(16,437)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(17,269)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(17,125)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(19,172)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(21,314)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(21,178)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(21,462)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(21,283)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(21,309)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(26,31)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(29,187)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(29,432)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(29,92)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(29,104)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(30,27)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(30,123)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(31,8)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(31,175)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(31,230)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(31,471)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(34,388)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(34,391)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(34,205)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(34,44)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(38,290)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(38,311)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(38,252)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(40,255)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(40,163)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(43,425)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(43,380)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(44,19)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(45,395)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(45,160)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(47,45)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(47,149)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(47,368)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(47,346)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(47,480)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(48,431)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(49,222)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(49,103)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(50,43)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(50,150)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(52,354)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(52,222)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(52,319)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(52,173)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(54,180)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(54,168)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(56,240)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(56,171)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(56,159)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(56,471)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(58,93)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(58,262)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(58,299)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(61,262)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(61,346)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(61,30)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(62,55)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(62,71)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(63,468)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(63,416)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(63,228)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(63,424)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(63,185)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(64,350)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(64,78)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(65,333)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(65,178)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(66,343)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(66,175)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(68,199)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(68,364)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(68,438)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(68,150)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(69,140)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(69,400)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(70,323)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(73,236)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(74,184)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(74,220)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(74,293)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(75,191)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(75,480)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(78,397)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(78,474)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(79,71)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(79,340)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(79,270)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(79,302)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(81,347)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(81,253)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(82,30)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(82,101)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(83,107)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(84,173)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(84,460)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(90,124)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(90,218)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(90,101)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(90,51)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(90,435)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(91,279)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(91,193)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(92,319)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(94,385)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(94,61)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(94,104)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(94,26)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(95,375)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(96,24)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(99,12)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(99,82)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(103,295)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(103,290)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(103,476)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(104,371)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(104,270)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(105,309)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(105,78)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(106,473)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(106,331)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(106,201)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(106,297)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(107,50)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(107,176)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(108,201)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(108,67)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(108,354)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(108,283)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(108,193)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(109,384)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(109,186)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(111,362)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(111,420)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(112,298)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(112,476)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(112,299)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(112,180)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(113,294)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(115,87)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(115,404)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(115,343)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(115,323)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(116,379)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(116,307)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(116,427)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(116,453)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(116,166)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(117,442)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(117,85)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(117,363)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(117,67)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(118,71)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(119,40)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(119,307)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(119,19)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(119,399)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(119,165)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(120,46)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(130,277)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(130,127)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(130,238)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(130,465)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(130,337)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(133,211)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(133,273)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(133,471)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(133,309)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(135,6)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(135,145)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(136,379)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(136,332)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(137,216)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(137,69)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(137,369)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(137,197)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(137,476)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(138,159)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(138,148)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(138,171)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(138,142)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(138,301)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(140,154)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(140,247)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(141,424)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(142,221)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(142,144)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(142,131)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(142,144)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(143,294)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(143,434)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(146,373)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(148,44)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(148,16)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(148,195)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(149,353)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(150,416)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(150,272)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(152,157)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(152,193)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(152,390)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(152,164)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(153,328)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(155,341)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(155,39)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(155,134)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(155,1)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(155,71)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(156,453)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(156,378)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(156,227)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(156,117)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(158,166)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(158,254)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(158,364)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(158,275)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(159,56)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(159,141)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(159,402)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(159,427)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(159,323)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(162,318)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(162,277)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(164,345)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(164,90)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(164,290)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(165,72)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(165,142)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(165,257)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(165,62)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(166,318)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(166,173)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(167,351)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(167,462)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(167,48)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(167,219)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(167,254)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(169,227)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(169,417)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(170,254)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(170,35)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(171,406)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(171,354)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(175,188)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(175,339)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(175,225)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(176,333)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(177,290)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(177,327)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(177,365)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(177,140)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(178,449)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(178,409)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(183,335)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(183,6)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(183,285)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(185,303)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(185,298)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(185,11)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(185,393)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(186,398)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(186,183)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(187,221)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(187,404)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(187,52)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(187,283)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(188,473)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(188,147)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(189,144)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(189,422)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(189,267)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(189,24)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(190,372)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(190,23)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(190,114)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(190,208)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(190,145)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(191,253)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(191,477)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(191,212)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(192,434)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(192,85)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(194,408)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(194,413)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(194,348)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(194,138)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(194,291)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(195,362)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(195,291)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(195,210)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(195,404)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(196,401)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(196,435)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(196,372)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(197,438)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(197,221)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(197,95)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(199,216)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(199,175)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(200,311)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(200,65)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(200,387)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(200,240)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(200,166)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(204,67)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(204,446)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(204,264)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(204,212)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(209,185)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(209,128)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(210,315)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(215,176)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(215,150)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(216,181)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(216,461)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(219,249)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(219,145)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(219,395)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(221,34)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(222,237)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(222,229)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(223,416)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(223,354)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(223,115)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(223,228)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(225,300)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(225,132)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(225,213)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(225,60)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(226,257)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(226,453)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(226,107)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(226,447)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(226,240)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(227,162)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(227,265)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(230,295)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(231,276)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(231,256)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(231,362)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(235,240)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(235,230)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(235,107)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(235,412)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(235,111)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(236,270)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(236,452)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(236,349)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(236,310)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(236,368)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(237,59)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(240,29)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(240,351)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(241,452)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(241,63)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(243,318)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(246,181)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(246,282)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(246,450)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(246,228)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(246,23)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(248,236)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(248,45)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(249,212)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(249,182)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(249,55)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(251,305)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(251,376)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(252,120)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(252,231)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(252,90)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(252,194)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(253,308)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(253,129)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(254,77)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(254,234)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(254,207)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(255,284)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(255,11)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(255,279)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(256,448)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(256,452)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(256,109)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(256,335)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(256,334)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(257,36)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(257,211)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(257,77)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(257,357)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(258,316)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(258,334)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(258,301)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(259,357)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(259,214)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(259,437)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(259,381)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(259,18)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(261,151)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(262,359)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(262,449)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(262,82)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(263,68)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(263,479)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(263,387)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(263,429)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(263,415)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(265,254)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(265,235)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(265,237)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(265,263)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(265,398)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(268,143)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(268,92)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(268,422)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(271,453)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(272,259)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(272,362)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(273,311)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(273,90)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(273,477)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(273,52)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(274,389)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(274,30)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(274,313)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(274,222)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(274,272)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(275,177)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(275,70)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(276,242)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(276,373)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(276,8)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(283,204)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(283,95)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(283,226)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(283,339)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(285,476)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(285,198)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(285,32)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(285,35)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(286,109)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(286,368)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(286,316)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(286,171)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(286,143)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(290,300)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(290,264)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(291,381)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(291,424)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(291,391)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(291,201)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(291,201)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(292,48)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(292,45)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(292,455)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(296,122)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(296,239)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(296,46)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(296,97)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(301,318)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(301,199)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(301,197)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(304,341)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(304,391)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(304,85)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(304,388)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(304,288)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(305,6)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(307,256)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(307,277)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(309,14)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(310,327)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(311,478)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(311,4)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(312,9)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(312,121)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(312,97)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(312,295)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(312,434)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(313,177)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(316,137)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(316,247)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(316,96)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(317,46)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(320,42)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(320,9)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(321,393)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(322,255)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(323,199)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(323,116)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(323,178)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(323,148)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(323,194)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(324,113)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(324,446)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(324,311)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(324,24)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(326,161)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(330,137)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(330,310)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(332,53)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(333,299)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(333,446)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(333,463)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(333,76)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(333,114)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(334,219)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(334,240)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(335,342)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(335,232)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(335,60)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(335,208)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(335,201)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(336,291)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(338,223)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(338,194)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(338,285)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(338,178)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(338,313)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(339,386)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(339,303)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(343,214)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(344,242)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(344,454)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(344,128)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(345,222)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(345,411)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(345,209)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(346,271)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(346,441)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(346,276)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(346,199)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(347,432)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(347,30)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(347,239)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(347,283)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(348,332)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(348,61)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(348,30)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(348,330)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(348,47)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(350,21)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(350,448)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(350,344)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(350,83)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(351,123)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(352,377)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(353,123)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(356,476)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(356,451)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(356,288)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(356,247)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(358,111)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(358,261)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(358,161)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(358,102)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(359,129)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(360,159)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(360,45)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(360,242)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(361,190)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(361,257)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(361,177)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(362,388)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(362,264)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(362,239)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(362,144)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(362,393)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(364,306)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(364,181)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(366,137)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(366,16)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(366,292)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(367,35)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(368,223)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(368,316)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(368,320)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(368,197)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(368,188)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(369,52)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(369,340)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(369,130)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(369,10)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(369,251)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(373,3)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(373,373)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(373,230)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(373,246)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(373,257)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(374,160)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(374,481)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(374,80)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(375,133)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(376,2)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(377,227)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(377,240)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(377,374)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(377,421)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(377,246)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(378,451)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(379,175)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(379,317)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(379,441)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(379,407)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(379,210)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(380,439)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(380,345)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(383,238)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(383,8)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(384,300)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(384,428)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(385,239)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(385,370)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(387,205)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(387,187)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(389,388)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(392,457)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(394,458)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(394,163)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(395,410)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(395,368)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(395,7)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(395,262)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(395,345)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(396,107)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(396,210)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(396,395)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(396,70)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(398,260)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(399,313)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(399,447)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(399,34)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(399,37)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(399,475)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(400,3)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(400,68)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(402,435)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(402,35)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(402,244)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(402,340)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(402,211)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(404,340)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(404,318)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(404,279)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(404,434)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(407,103)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(407,77)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(407,368)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(408,368)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(408,75)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(408,376)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(410,131)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(410,124)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(410,59)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(410,250)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(411,336)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(411,452)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(412,69)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(413,67)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(413,129)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(414,295)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(415,87)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(416,90)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(416,81)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(416,310)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(416,52)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(417,131)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(417,53)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(417,319)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(419,237)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(419,394)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(419,262)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(419,79)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(419,156)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(420,179)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(420,147)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(421,405)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(421,160)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(421,160)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(422,44)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(422,329)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(422,430)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(422,364)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(422,146)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(423,476)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(423,315)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(423,372)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(426,321)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(427,65)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(427,388)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(427,278)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(427,335)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(427,340)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(429,127)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(429,282)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(429,101)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(430,289)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(430,279)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(430,193)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(430,76)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(430,318)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(432,388)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(432,163)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(432,124)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(436,37)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(436,181)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(436,213)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(436,434)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(439,29)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(439,421)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(439,102)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(440,449)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(440,433)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(440,127)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(440,284)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(441,184)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(441,481)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(441,18)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(443,25)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(443,300)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(444,36)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(444,184)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(444,80)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(444,328)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(444,417)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(447,355)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(448,185)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(448,150)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(452,474)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(452,188)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(453,410)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(455,136)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(455,60)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(457,196)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(457,429)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(457,352)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(462,161)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(462,214)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(463,12)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(463,72)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(463,53)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(463,10)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(464,425)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(466,415)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(466,21)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(466,113)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(467,417)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(467,148)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(467,471)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(468,90)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(468,443)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(468,471)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(468,453)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(468,66)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(469,124)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(469,114)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(469,160)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(470,163)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(470,76)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(470,145)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(470,71)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(471,85)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(471,126)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(471,127)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(472,243)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(472,268)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(472,96)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(472,321)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(472,411)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(475,139)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(477,220)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(477,10)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(477,233)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(478,267)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(478,134)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(478,266)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(479,64)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(480,245)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(480,46)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(480,461)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(480,450)
INSERT INTO FoodChainLink(fk_idConsumer, fk_idFood)
VALUES(480,282)