INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Acacia', 'Acacia pseudonigrescens', 2, 5, 1) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Acer', 'Acer pentaphyllum', 2, 4, 2) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Actinella', 'Actinella giramica', 1, 2, 3)
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Adélie penguin', 'Pygoscelis adeliae', 1, 3, 4) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('African candelabra', 'Euphorbia ammak', 2, 4, 5) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('African spoonbill', 'Platalea alba', 1, 3, 6) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Aglaia', 'Aglaia brassii', 1, 3, 7) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Aiphanes palm', 'Aiphanes grandis', 1, 3, 8) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Alangium', 'Alangium longiflorum', 2, 5, 9) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Alerce', 'Fitzroya cupressoides', 2, 5, 10) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Allophylus', 'Allophylus rhomboidalis', 2, 5, 11) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Aloe', 'Aloe juddii', 2, 4, 12)
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Alveopora coral', 'Alveopora tizardi', 2, 4, 13) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Amatola toad', 'Vandijkophrynus amatolicus', 1, 2, 14) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('American coot', 'Fulica americana', 2, 5, 15) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Amorphophallus', 'Amorphophallus verticillatus', 1, 3, 16) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Anatipes robber frog', 'Strabomantis anatipes', 1, 2, 17) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Andrachne', 'Andrachne aspera', 2, 5, 18) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Annulated sea snake', 'Hydrophis cyanocinctus', 1, 2, 19) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Anthocleista', 'Anthocleista microphylla', 2, 5, 20) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Apennine brown bear', 'Ursus arctos marsicanus', 1, 3, 21) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Aquilaria', 'Aquilaria hirta', 2, 5, 22) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Araripe manakin', 'Antilophia bokermanni', 2, 4, 23) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Arenaria', 'Arenaria radians', 2, 5, 24) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Arundo', 'Arundo donax', 2, 4, 25) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Asian openbill', 'Anastomus oscitans', 1, 1, 26) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Aspidosperma', 'Aspidosperma polyneuron', 2, 5, 27) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Astreopora coral', 'Astreopora incrustans', 2, 5, 28) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Atlantic sailfish', 'Istiophorus albicans', 1, 1, 29) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Aulonocara Fort Maguire', 'Aulonocara hansbaenschi', 1, 2, 30) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Azure-shouldered tanager', 'Thraupis cyanoptera', 1, 3, 31) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Baishan fir', 'Abies beshanzuensis', 2, 5, 32) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bambangan', 'Mangifera pajang', 2, 5, 33) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bangana', 'Bangana behri', 1, 3, 34) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Barabattoia coral', 'Barabattoia laddi', 2, 5, 35) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Barleria', 'Barleria grandis', 2, 4, 36) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bauhinia', 'Bauhinia paradisi', 2, 4, 37) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bearded tooth', 'Hericium erinaceum', 1, 1, 38) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Begonia', 'Begonia hitchcockii', 2, 4, 39) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bellamya', 'Bellamya phthinotropis', 1, 3, 40) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Berberis', 'Berberis pindilicensis', 2, 4, 41) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bewick’s swan', 'Cygnus columbianus bewickii', 2, 4, 42) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Birdsnest coral', 'Seriatopora caliendrum', 1, 3, 43) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Black abalone', 'Haliotis cracherodii', 1, 1, 44) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Black giant squirrel', 'Ratufa bicolor', 1, 3, 45) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Black pennant', 'Selysiothemis nigra', 2, 5, 46) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Black-and-gold tanager', 'Bangsia melanochlamys', 1, 1, 47) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Black-capped capuchin', 'Cebus apella', 1, 2, 48) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Black-masked finch', 'Coryphaspiza melanotis', 1, 1, 49) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Black-winged stilt', 'Himantopus himantopus', 1, 1, 50) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Blakea', 'Blakea rotundifolia', 2, 5, 51) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Blossomcrown', 'Anthocephala floriceps', 1, 3, 52) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Blue shined grasshopper', 'Sphingonotus rubescens', 2, 4, 53) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Blue-headed pitta', 'Pitta baudii', 1, 2, 54) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Boerhavia', 'Boerhavia elegans', 2, 4, 55) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bolitoglossa', 'Bolitoglossa guaramacalensis', 1, 1, 56) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bonnetia', 'Bonnetia lanceifolia', 2, 5, 57) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Boreal toad', 'Anaxyrus boreas', 1, 3, 58) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bottlebush', 'Paranomus sceptrum-gustavianus', 2, 5, 59) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Brachyotum', 'Brachyotum azuayense', 2, 4, 60) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Brazilian merganser', 'Mergus octosetaceus', 1, 1, 61) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bright-eyed frog', 'Boophis calcaratus', 1, 2, 62) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bromeliad', 'Aechmea aculeatosepala', 1, 3, 63) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Brook barbel', 'Barbus caninus', 1, 1, 64) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Brown noddy', 'Anous stolidus', 1, 1, 65) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Brown-spotted rockcod', 'Epinephelus andersoni', 1, 1, 66) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Buddleja', 'Buddleja megalocephala', 2, 4, 67) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bulbostylis', 'Bulbostylis lichtensteiniana', 1, 3, 68) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Burmeistera', 'Burmeistera resupinata', 1, 3, 69) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Bush hyrax', 'Heterohyrax brucei', 1, 1, 70) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Byttneria', 'Byttneria minytricha', 2, 5, 71) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cactus', 'Astrophytum ornatum', 2, 4, 72) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cactus', 'Peniocereus rosei', 1, 1, 73) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cairo spiny mouse', 'Acomys cahirinus', 1, 2, 74) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Calea', 'Calea kingii', 1, 1, 75) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Calophyllum', 'Calophyllum cordato-oblongum', 2, 4, 76) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Calyptranthes', 'Calyptranthes rostrata', 2, 5, 77) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Campo miner', 'Geositta poeciloptera', 1, 2, 78) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cape Fear shiner', 'Notropis mekistocholas', 1, 2, 79) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Capparis', 'Capparis sprucei', 2, 4, 80) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Caribbean dove', 'Leptotila jamaicensis', 1, 3, 81) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Caroxylon', 'Caroxylon cyclophyllum', 1, 3, 82) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Caspian tern', 'Sterna caspia', 1, 1, 83) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Caucasian alder', 'Alnus subcordata', 1, 2, 84) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Centaurea', 'Centaurea princeps', 2, 5, 85) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Centropogon', 'Centropogon pilalensis', 2, 5, 86) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cestrum', 'Cestrum chimborazinum', 2, 5, 87) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Chalk-fronted corporal', 'Libellula julia', 2, 4, 88) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Chassalia', 'Chassalia petitiana', 2, 4, 89) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Chestnut-backed buttonquail', 'Turnix castanotus', 1, 2, 90) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Chimanimani cycad', 'Encephalartos chimanimaniensis', 1, 2, 91) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Chinese softshell turtle', 'Pelodiscus sinensis', 1, 2, 92) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Chloris', 'Chloris gayana', 2, 5, 93) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Christmas hawk-owl', 'Ninox natalis', 1, 1, 94) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cicer', 'Cicer canariense', 1, 1, 95) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cichlid', 'Labidochromis zebroides', 1, 2, 96) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cirolanid isopod', 'Arubolana aruboides', 2, 4, 97) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Clay fan-foot moth', 'Paracolax tristalis', 2, 5, 98) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cliff swallow', 'Petrochelidon pyrrhonota', 1, 3, 99) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Clynotis', 'Clynotis albobarbatus', 2, 4, 100) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cocculus', 'Cocculus balfourii', 2, 5, 101) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Coelocarpum', 'Coelocarpum haggierensis', 2, 4, 102) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Collared iguana', 'Oplurus cuvieri', 1, 3, 103) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Columnea', 'Columnea schimpffii', 1, 2, 104) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Common blue', 'Polyommatus icarus', 1, 1, 105) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Common five-lined skink', 'Plestiodon fasciatus', 1, 2, 106) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Common nightingale', 'Luscinia megarhynchos', 1, 1, 107) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Common seahorse', 'Hippocampus kuda', 1, 3, 108) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Concertina plant', 'Crassula rupestris', 1, 1, 109) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Conus', 'Conus crotchii', 2, 4, 110) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Coosawattee crayfish', 'Cambarus coosawattae', 1, 1, 111) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Corallocarpus', 'Corallocarpus epigaeus', 1, 2, 112) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cornus', 'Cornus disciflora', 1, 3, 113) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Couepia', 'Couepia joaquinae', 2, 4, 114) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Craterispermum', 'Craterispermum montanum', 1, 3, 115) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Crested duck', 'Lophonetta specularioides', 1, 1, 116) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cristilabrum', 'Cristilabrum spectaculum', 1, 2, 117) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Croton', 'Croton aubrevillei', 1, 2, 118) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cryptopotamon', 'Cryptopotamon anacoluthon', 1, 1, 119) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cucumis', 'Cucumis prophetarum', 1, 2, 120) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cycad', 'Cycas calcicola', 2, 5, 121) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cycad', 'Macrozamia parcifolia', 2, 4, 122) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cycad', 'Dioon tomasellii', 2, 4, 123) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cycad', 'Cycas macrocarpa', 2, 4, 124) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cycad', 'Microcycas calocoma', 2, 5, 125) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Cymbopetalum', 'Cymbopetalum baillonii', 2, 4, 126) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dactyladenia', 'Dactyladenia hirsuta', 2, 5, 127) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dalbergia', 'Dalbergia urschii', 2, 5, 128) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Danube crested newt', 'Triturus dobrogicus', 2, 5, 129) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Darkedged splitfin', 'Girardinichthys multiradiatus', 1, 2, 130) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Decim periodical cicada', 'Magicicada septendecim', 2, 5, 131) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dendropanax', 'Dendropanax alberti-smithii', 2, 4, 132) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Desert viper', 'Daboia deserti', 1, 3, 133) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Diademed sifaka', 'Propithecus diadema', 2, 5, 134) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Digera', 'Digera muricata', 1, 3, 135) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Diospyros', 'Diospyros bejaudii', 1, 1, 136) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Diplycosia', 'Diplycosia pilosa', 1, 3, 137) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dipterocarpus', 'Dipterocarpus eurynchus', 1, 1, 138) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dorstenia', 'Dorstenia socotrana', 2, 4, 139) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dracula minnow', 'Danionella dracula', 1, 3, 140) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dryobalanops', 'Dryobalanops beccarii', 1, 3, 141) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Duncan coral', 'Duncanopsammia axifuga', 1, 3, 142) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dwarf bearded dragon', 'Pogona minor', 1, 2, 143) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dyerophytum', 'Dyerophytum socotranum', 2, 4, 144) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Dypsis', 'Dypsis boiviniana', 2, 5, 145) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Eastern Cape rocky', 'Sandelia bainsii', 1, 1, 146) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Eastern redbud', 'Cercis canadensis', 2, 5, 147) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Echium', 'Echium acanthocarpum', 1, 1, 148) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Egyptian pygmy shrew', 'Crocidura religiosa', 1, 1, 149) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Elaphoglossum', 'Elaphoglossum antisanae', 1, 1, 150) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Elusive skimmer', 'Orthetrum rubens', 2, 4, 151) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Endemic predatory shrimp', 'Procaris ascensionis', 1, 3, 152) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Erica', 'Erica recurvata', 1, 2, 153) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Erodium', 'Erodium glaucophyllum', 2, 5, 154) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Escambia map turtle', 'Graptemys ernsti', 1, 2, 155) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Estuarine pipefish', 'Syngnathus watermeyeri', 1, 3, 156) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Eugenia', 'Eugenia taipingensis', 2, 4, 157) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Euphorbia', 'Euphorbia cap-saintemariensis', 1, 1, 158) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Euphorbia', 'Euphorbia bourgeana', 1, 1, 159) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Euphorbia', 'Euphorbia ogadenensis', 2, 5, 160) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Euphorbia', 'Euphorbia burgeri', 2, 4, 161) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Eurasian golden oriole', 'Oriolus oriolus', 1, 2, 162) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Faber’s fir', 'Abies fabri', 2, 5, 163) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('False killer whale', 'Pseudorca crassidens', 1, 1, 164) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Favites coral', 'Favites spinosa', 1, 3, 165) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ficus', 'Ficus faulkneriana', 1, 2, 166) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Fig', 'Ficus ramiflora', 1, 1, 167) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Fire coral', 'Millepora platyphylla', 2, 5, 168) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Flatback turtle', 'Natator depressus', 1, 1, 169) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Florida scrub-jay', 'Aphelocoma coerulescens', 1, 3, 170) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Forest banana frog', 'Afrixalus sylvaticus', 1, 3, 171) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Four-spotted orchid', 'Orchis quadripunctata', 2, 5, 172) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('French Broad Crayfish', 'Cambarus reburrus', 2, 4, 173) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Freziera', 'Freziera echinata', 2, 4, 174) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Gaertnera', 'Gaertnera hirtiflora', 1, 1, 175) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Galapagos land snail', 'Bulimulus ustulatus', 1, 1, 176) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Gannet', 'Morus bassanus', 1, 3, 177) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Garo hills bubble-nest frog', 'Philautus garo', 1, 2, 178) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Genista', 'Genista benehoavensis', 2, 4, 179) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Geranium', 'Geranium antisanae', 2, 5, 180) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Giant genet', 'Genetta victoriae', 2, 4, 181) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Giant trevally', 'Caranx ignobilis', 2, 5, 182) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Gladiolus', 'Gladiolus pole-evansii', 1, 1, 183) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Glycosmis', 'Glycosmis longisepala', 2, 4, 184) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Golden hamster', 'Mesocricetus auratus', 1, 2, 185) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Golden-backed weaver', 'Ploceus jacksoni', 1, 1, 186) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Goodman’s mouse lemur', 'Microcebus lehilahytsara', 1, 1, 187) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Grahams crayfish snake', 'Regina grahamii', 1, 2, 188) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Gray langur', 'Semnopithecus hector', 1, 3, 189) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Great frigatebird', 'Fregata minor', 1, 2, 190) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Greater Egyptian jerboa', 'Jaculus orientalis', 1, 3, 191) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Greater short-toed lark', 'Calandrella brachydactyla', 1, 3, 192) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Green-backed kingfisher', 'Actenoides monachus', 2, 4, 193) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Grewcock’s sportive lemur', 'Lepilemur grewcockorum', 1, 1, 194) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Grey squirrel', 'Sciurus carolinensis', 1, 1, 195) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Grey-headed kingfisher', 'Halcyon leucocephala', 1, 2, 196) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Grosbeak bunting', 'Nesospiza wilkinsi', 1, 3, 197) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Guarea', 'Guarea humaitensis', 2, 5, 198) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Guioa', 'Guioa novobritannica', 1, 1, 199) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Gustavia', 'Gustavia fosteri', 1, 1, 200) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Gypsophila', 'Gypsophila montana', 2, 5, 201) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hainan knobby newt', 'Tylototriton hainanensis', 2, 5, 202) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Halocarpus', 'Halocarpus kirkii', 2, 4, 203) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Harebell', 'Campanula rotundifolia', 1, 2, 204) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hawaiian jewel-orchid', 'Anoectochilus sandvicensis', 2, 4, 205) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hedyosmum', 'Hedyosmum purpurascens', 2, 4, 206) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Heliotropium', 'Heliotropium dentatum', 2, 5, 207) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Henkels Yellowwood', 'Podocarpus henkelii', 2, 4, 208) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Herringbone butterflyfish', 'Chaetodon triangulum', 1, 3, 209) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Highland guan', 'Penelopina nigra', 1, 3, 210) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hispaniolan solenodon', 'Solenodon paradoxus', 2, 5, 211) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Homalium', 'Homalium hypolasium', 2, 4, 212) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hood coral', 'Stylophora wellsi', 2, 4, 213) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hopea', 'Hopea mindanensis', 2, 4, 214) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Horse-fly', 'Chrysops relictus', 1, 1, 215) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Huemul', 'Hippocamelus bisulcus', 1, 2, 216) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hydnocarpus', 'Hydnocarpus filipes', 2, 4, 217) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Hypericum', 'Hypericum fieriense', 2, 4, 218) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Iberus', 'Iberus gualtieranus', 1, 3, 219) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ilex', 'Ilex glabella', 2, 4, 220) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Indian balloon frog', 'Uperodon globulosus', 1, 1, 221) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Indian yellow-nosed albatross', 'Thalassarche carteri', 1, 3, 222) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Inga', 'Inga bella', 1, 3, 223) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Inga', 'Inga macrantha', 2, 5, 224) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Iris lorikeet', 'Psitteuteles iris', 1, 2, 225) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Isthmohyla', 'Isthmohyla insolita', 1, 1, 226) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Jabiru stork', 'Jabiru mycteria', 1, 1, 227) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Japanese douglas-fir', 'Pseudotsuga japonica', 2, 4, 228) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Jersey cudweed', 'Pseudognaphalium luteo-album', 2, 5, 229) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Juba', 'Ptychochromis inornatus', 1, 2, 230) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Justicia', 'Justicia heterocarpa', 1, 1, 231) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Karoo cycad', 'Encephalartos lehmannii', 2, 5, 232) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Kayea', 'Kayea coriacea', 2, 4, 233) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Keys boronia', 'Boronia keysii', 2, 4, 234) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Kirtland’s warbler', 'Dendroica kirtlandii', 1, 1, 235) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Knob coral', 'Favia rotundata', 1, 3, 236) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Koklass pheasant', 'Pucrasia macrolopha', 1, 2, 237) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Kroombit tinker frog', 'Taudactylus pleione', 2, 5, 238) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Lace coral', 'Distichopora violacea', 2, 5, 239) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Lake Magadi tilapia', 'Alcolapia grahami', 1, 3, 240) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Large copper butterfly', 'Lycaena dispar', 1, 1, 241) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Largeleaf sandwort', 'Moehringia macrophylla', 2, 4, 242) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Launaea', 'Launaea fragilis', 1, 2, 243) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Leaf coral', 'Pavona minuta', 2, 4, 244) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ledermanniella', 'Ledermanniella keayi', 2, 4, 245) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Leopard torpedo', 'Torpedo panthera', 1, 2, 246) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Lesser leaf-nosed bat', 'Hipposideros pendleburyi', 2, 4, 247) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Lesser water-plantain', 'Baldellia ranunculoides', 1, 1, 248) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Liben lark', 'Heteromirafra sidamoensis', 1, 2, 249) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Light red meranti', 'Shorea macrophylla', 2, 5, 250) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Limnonectes', 'Limnonectes dabanus', 1, 1, 251) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Liophis', 'Liophis atraventer', 1, 1, 252) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Little stint', 'Calidris minuta', 1, 2, 253) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Loesenera', 'Loesenera talbotii', 1, 2, 254) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Long-fingered bat', 'Myotis capaccinii', 1, 2, 255) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Long-tailed parakeet', 'Psittacula longicauda', 1, 1, 256) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Lord Howe Island stick insect', 'Dryococelus australis', 1, 2, 257) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Low nightshade', 'Solanum humile', 1, 1, 258) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Lynchs stubfoot toad', 'Atelopus lynchi', 1, 2, 259) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mackillingins gerbil', 'Gerbillus mackillingini', 2, 4, 260) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Madagascar frog', 'Mantidactylus striatus', 1, 2, 261) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Madder', 'Hallea stipulosa', 1, 3, 262) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Magnificent broodfrog', 'Pseudophryne covacevichae', 1, 1, 263) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Magnolia', 'Magnolia wilsonii', 2, 4, 264) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Malayan snail-eating turtle', 'Malayemys subtrijuga', 1, 1, 265) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Malpighia', 'Malpighia harrisii', 2, 5, 266) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mammillaria', 'Mammillaria albicoma', 2, 5, 267) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Manettia', 'Manettia skutchii', 1, 1, 268) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Manilkara', 'Manilkara multifida', 2, 5, 269) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Maple silkwood', 'Flindersia pimenteliana', 2, 4, 270) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Marsh deer', 'Blastocerus dichotomus', 1, 1, 271) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Martelia', 'Martelia tanganyicensis', 1, 1, 272) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Matano ricefish', 'Oryzias matanensis', 1, 1, 273) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mauve Coopernookia', 'Coopernookia georgei', 1, 1, 274) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mccord’s box turtle', 'Cuora mccordi', 1, 1, 275) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Megalomyrmex', 'Megalomyrmex symmetochus', 1, 3, 276) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Memecylon', 'Memecylon teitense', 2, 4, 277) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Meriania', 'Meriania panamensis', 2, 5, 278) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Metteniusa', 'Metteniusa edulis', 2, 4, 279) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Michaux’s sedge', 'Carex michauxiana', 2, 5, 280) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Miconia', 'Miconia prietoi', 2, 4, 281) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Miconia', 'Miconia mediocris', 2, 5, 282) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Millettia', 'Millettia sericantha', 1, 1, 283) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mindanao miniature-babbler', 'Micromacronus sordidus', 2, 4, 284) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mitred leaf monkey', 'Presbytis melalophos', 1, 2, 285) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Moluccan megapode', 'Eulipoa wallacei', 1, 1, 286) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Monomorium', 'Monomorium talbotae', 2, 4, 287) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Montipora coral', 'Montipora altasepta', 2, 4, 288) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Morella', 'Morella arborea', 2, 5, 289) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mount Glorious torrent frog', 'Taudactylus diurnus', 1, 2, 290) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mountain serpent eagle', 'Spilornis kinabaluensis', 1, 2, 291) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mukia', 'Mukia maderaspatana', 1, 1, 292) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Mushroomtongue salamander', 'Bolitoglossa conanti', 2, 4, 293) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Myosotis', 'Myosotis azorica', 2, 5, 294) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Napoleonaea', 'Napoleonaea lutea', 2, 4, 295) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Nassau grouper', 'Epinephelus striatus', 1, 2, 296) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Nectandra', 'Nectandra guadaripo', 2, 4, 297) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Nectandra', 'Nectandra utilis', 2, 4, 298) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Neotropical otter', 'Lontra longicaudis', 2, 4, 299) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('New England cottontail', 'Sylvilagus transitionalis', 2, 5, 300) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Nilgiri blue robin', 'Myiomela major', 1, 3, 301) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Nodding broomrape', 'Orobanche cernua', 2, 5, 302) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Northern California black walnut', 'Juglans californica', 2, 4, 303) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Northern harrier', 'Circus cyaneus', 1, 2, 304) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Norwegian mugwort', 'Artemisia norvegica', 1, 1, 305) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Nuragica columbine', 'Aquilegia nuragica', 2, 5, 306) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ocellate river stingray', 'Potamotrygon motoro', 1, 3, 307) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ocotea', 'Ocotea porosa', 2, 5, 308) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Okapi', 'Okapia johnstoni', 1, 3, 309) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Olive-backed pipit', 'Anthus hodgsoni', 1, 2, 310) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ononis', 'Ononis viscosa', 1, 1, 311) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Orange-bellied antwren', 'Terenura sicki', 1, 2, 312) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Orchid', 'Paphiopedilum tigrinum', 1, 3, 313) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Orchid', 'Dracula vampira', 2, 5, 314) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Orchid', 'Eulophia hians', 2, 5, 315) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Oregon spotted frog', 'Rana pretiosa', 1, 3, 316) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Orinoco crocodile', 'Crocodylus intermedius', 1, 3, 317) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Orthosia', 'Orthosia ellemannii', 2, 5, 318) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ozark cavefish', 'Amblyopsis rosae', 2, 5, 319) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pacific reef-egret', 'Egretta sacra', 1, 3, 320) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Palaquium', 'Palaquium thwaitesii', 1, 2, 321) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pale-throated three-toed sloth', 'Bradypus tridactylus', 1, 1, 322) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pallas’s fish-eagle', 'Haliaeetus leucoryphus', 1, 1, 323) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pampas fox', 'Pseudalopex gymnocercus', 1, 3, 324) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Paradrymonia', 'Paradrymonia binata', 2, 5, 325) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Parkers antbird', 'Cercomacra parkeri', 1, 3, 326) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Partula snail', 'Partula thalia', 2, 4, 327) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Passion flower', 'Passiflora anfracta', 2, 4, 328) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pavetta', 'Pavetta axillipara', 2, 4, 329) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Peat swamp frog', 'Limnonectes malesianus', 1, 3, 330) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Peperomia', 'Peperomia clivigaudens', 2, 4, 331) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Periah peak caecilian', 'Gegeneophis carnosus', 1, 2, 332) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Peruvian martin', 'Progne murphyi', 1, 3, 333) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Phalaenopsis', 'Phalaenopsis pulcherrima', 1, 1, 334) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Philippine cockatoo', 'Cacatua haematuropygia', 1, 2, 335) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pholidocarpus', 'Pholidocarpus macrocarpus', 1, 1, 336) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Picrasma', 'Picrasma excelsa', 2, 4, 337) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pillar coral', 'Dendrogyra cylindrus', 1, 1, 338) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pink-headed duck', 'Rhodonessa caryophyllacea', 1, 2, 339) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Piper', 'Piper cutucuense', 2, 4, 340) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Piptostigma', 'Piptostigma giganteum', 2, 5, 341) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pitcher plant', 'Nepenthes distillatoria', 2, 5, 342) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Piura water frog', 'Telmatobius ignavus', 1, 2, 343) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Platyla', 'Platyla foliniana', 1, 2, 344) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Plumbeous antvireo', 'Dysithamnus plumbeus', 1, 1, 345) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Point-nosed frog', 'Clinotarsus alticola', 1, 1, 346) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Polylepis', 'Polylepis crista-galli', 1, 3, 347) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pomugu wrinkled ground frog', 'Platymantis akarithyma', 1, 1, 348) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pouteria', 'Pouteria benai', 2, 4, 349) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pouteria', 'Pouteria hotteana', 1, 1, 350) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Prestonia', 'Prestonia parvifolia', 1, 2, 351) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Prismatomeris', 'Prismatomeris andamanica', 1, 3, 352) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pristimantis', 'Pristimantis truebae', 1, 3, 353) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pritchardia', 'Pritchardia forbesiana', 2, 4, 354) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pseudoacontias', 'Pseudoacontias menamainty', 2, 5, 355) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pseudophilautus', 'Pseudophilautus stellatus', 1, 2, 356) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Psychotria', 'Psychotria clusioides', 2, 4, 357) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ptychadena', 'Ptychadena newtoni', 1, 3, 358) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Puncture vine', 'Tribulus omanense', 1, 2, 359) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Putitor mahseer', 'Tor putitora', 1, 3, 360) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Pyrenean desman', 'Galemys pyrenaicus', 1, 1, 361) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Quercus', 'Quercus galeanensis', 1, 2, 362) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rafflesia', 'Rafflesia keithii', 2, 5, 363) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rams-head ladys-slipper', 'Cypripedium arietinum', 1, 3, 364) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ravenea', 'Ravenea hildebrandtii', 2, 4, 365) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Red deer', 'Cervus elaphus', 1, 1, 366) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Red-bellied guenon', 'Cercopithecus erythrogaster', 1, 2, 367) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Red-finned blue-eye', 'Scaturiginichthys vermeilipinnis', 1, 1, 368) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Red-necked stint', 'Calidris ruficollis', 1, 3, 369) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Reddish buff moth', 'Acosmetia caliginosa', 2, 4, 370) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Reindeer lichen', 'Cladonia mediterranea', 2, 4, 371) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rhamnus', 'Rhamnus integrifolia', 2, 5, 372) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ring-tailed lemur', 'Lemur catta', 1, 1, 373) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Riobamba marsupial frog', 'Gastrotheca riobambae', 1, 2, 374) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Robber frog', 'Eleutherodactylus armstrongi', 1, 1, 375) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rock snail', 'Codringtonia codringtonii', 1, 2, 376) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rondeletia', 'Rondeletia amplexicaulis', 1, 1, 377) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rota white-eye', 'Zosterops rotensis', 1, 2, 378) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rubus', 'Rubus azuayensis', 1, 1, 379) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rufous treepie', 'Dendrocitta vagabunda', 1, 1, 380) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Rufous-winged sunbird', 'Nectarinia rufipennis', 2, 5, 381) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ruta', 'Ruta microcarpa', 2, 4, 382) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sadleriana', 'Sadleriana cavernosa', 1, 3, 383) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Saint Pauls gregory', 'Stegastes sanctipauli', 1, 2, 384) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('San Francisco forktail', 'Ischnura gemina', 1, 3, 385) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sandoricum', 'Sandoricum vidalii', 2, 4, 386) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Santa Rosa cochran frog', 'Nymphargus megacheirus', 1, 3, 387) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sarcosoma spp.', 'Sarcosoma globosum', 2, 5, 388) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Savanna shrew', 'Crocidura fulvastra', 1, 2, 389) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Scaphopetalum', 'Scaphopetalum parvifolium', 2, 4, 390) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Schokari sand racer', 'Psammophis schokari', 2, 4, 391) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Scree skink', 'Oligosoma waimatense', 1, 1, 392) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Seablite', 'Suaeda aegyptiaca', 2, 4, 393) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Semi-collared flycatcher', 'Ficedula semitorquata', 1, 2, 394) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Serval', 'Leptailurus serval', 1, 1, 395) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sharp-ribbed salamander', 'Pleurodeles waltl', 1, 1, 396) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Shorea', 'Shorea astylosa', 2, 4, 397) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Shorea', 'Shorea pallescens', 1, 3, 398) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Short-tailed pygmy monitor', 'Varanus brevicauda', 1, 3, 399) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Siamese crocodile', 'Crocodylus siamensis', 1, 1, 400) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sideroxylon', 'Sideroxylon peninsulare', 2, 5, 401) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Silky short-tailed bat', 'Carollia brevicauda', 1, 2, 402) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Siphocampylus', 'Siphocampylus furax', 2, 5, 403) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Slender blenny', 'Tanyemblemaria alleni', 1, 2, 404) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Slipper orchid', 'Paphiopedilum barbatum', 2, 4, 405) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Small skimmer', 'Orthetrum taeniolatum', 2, 4, 406) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Smiths blue butterfly', 'Euphilotes enoptes smithi', 1, 3, 407) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Snow petrel', 'Pagodroma nivea', 1, 1, 408) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Solanum', 'Solanum sibundoyense', 2, 4, 409) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sonoran mud turtle', 'Kinosternon sonoriense', 1, 2, 410) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('South American tern', 'Sterna hirundinacea', 1, 3, 411) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Southern frog', 'Telmatobius sibiricus', 1, 3, 412) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Southern rockhopper penguin', 'Eudyptes chrysocome', 1, 2, 413) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Spanish moss', 'Tillandsia usneoides', 1, 3, 414) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Spine-tailed sea snake', 'Aipysurus eydouxii', 1, 2, 415) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Spiny-breasted giant frog', 'Paa fasciculispina', 1, 1, 416) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Spotted houndshark', 'Triakis maculata', 1, 3, 417) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Spur-winged lapwing', 'Vanellus spinosus', 2, 5, 418) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sri Lanka wood pigeon', 'Columba torringtoniae', 1, 1, 419) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Staghorn coral', 'Acropora jacquelineae', 1, 2, 420) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Staghorn coral', 'Acropora acuminata', 1, 2, 421) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Star cactus', 'Astrophytum asterias', 1, 3, 422) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Steiners shrub frog', 'Pseudophilautus steineri', 1, 2, 423) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Steriphoma', 'Steriphoma urbani', 2, 4, 424) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Stoliczia', 'Stoliczia perlensis', 2, 4, 425) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Stony coral', 'Euphyllia cristata', 1, 1, 426) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Striped lychnis moth', 'Shargacucullia lychnitis', 1, 3, 427) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Stylocoeniella coral', 'Stylocoeniella cocosensis', 2, 4, 428) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sulawesi hornbill', 'Penelopides exarhatus', 1, 2, 429) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Sundevall’s jird', 'Meriones crassus', 1, 2, 430) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Swamp cypress', 'Actinostrobus pyramidalis', 2, 4, 431) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Swynnertons forest robin', 'Swynnertonia swynnertoni', 1, 3, 432) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tabebuia', 'Tabebuia oligolepis', 2, 4, 433) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Taiwan incense-cedar', 'Calocedrus formosana', 2, 5, 434) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tambourissa', 'Tambourissa ficus', 2, 5, 435) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tasmanian devil', 'Sarcophilus harrisii', 1, 2, 436) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Temminck’s tragopan', 'Tragopan temminckii', 2, 5, 437) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Ternstroemia', 'Ternstroemia landae', 2, 5, 438) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Thelypteris', 'Thelypteris bonapartii', 1, 3, 439) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Thousand dollar knife fish', 'Chitala chitala', 1, 2, 440) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tiassale liptena', 'Liptena tiassale', 1, 2, 441) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tilapia', 'Tilapia bythobathes', 2, 4, 442) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tokoeka', 'Apteryx australis', 1, 2, 443) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Torreya', 'Torreya jackii', 1, 3, 444) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Trichilia', 'Trichilia chirriactensis', 2, 5, 445) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Trigonella', 'Trigonella stellata', 2, 5, 446) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tropheops', 'Tropheops gracilior', 1, 2, 447) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Tsingymantis', 'Tsingymantis antitra', 1, 1, 448) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Turbinicarpus', 'Turbinicarpus lophophoroides', 2, 4, 449) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Turraea', 'Turraea socotrana', 2, 4, 450) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Uncinia', 'Uncinia subsacculata', 2, 5, 451) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Usambara eagle-owl', 'Bubo vosseleri', 1, 3, 452) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Valdina farms salamander', 'Eurycea troglodytes', 1, 1, 453) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Vatica', 'Vatica chinensis', 2, 4, 454) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Vatica', 'Vatica badiifolia', 1, 3, 455) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Vepris', 'Vepris samburuensis', 2, 4, 456) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Vincentella', 'Vincentella densiflora', 1, 1, 457) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Vismia', 'Vismia jefensis', 2, 5, 458) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Wai‘oli Valley pritchardia', 'Pritchardia perlmanii', 2, 4, 459) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Warburgia', 'Warburgia elongata', 2, 5, 460) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Water scorpion', 'Nepa cinerea', 2, 4, 461) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Wedge-tailed eagle', 'Aquila audax', 1, 2, 462) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Western hoolock gibbon', 'Hoolock hoolock', 1, 2, 463) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Wettinia', 'Wettinia verruculosa', 1, 2, 464) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('White mahogany', 'Khaya anthotheca', 2, 5, 465) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('White-bellied frog', 'Geocrinia alba', 1, 3, 466) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('White-cheeked pintail', 'Anas bahamensis', 1, 1, 467) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('White-headed langur', 'Trachypithecus poliocephalus', 1, 1, 468) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('White-throated robin', 'Irania gutturalis', 1, 3, 469) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Whitetip reef shark', 'Triaenodon obesus', 1, 2, 470) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Wild pelea', 'Melicope ovalis', 1, 2, 471) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Winghead shark', 'Eusphyra blochii', 1, 1, 472) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Woodland jumping mouse', 'Napaeozapus insignis', 2, 5, 473) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Wrinkle coral', 'Coscinaraea crassa', 2, 5, 474) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Yaqui chub', 'Gila purpurea', 1, 2, 475) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Yellow rail', 'Coturnicops noveboracensis', 2, 4, 476) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Yellow-breasted chat', 'Icteria virens', 1, 2, 477) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Yellow-naped Amazon', 'Amazona auropalliata', 1, 2, 478) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Yellowmouth grouper', 'Mycteroperca interstitialis', 1, 1, 479) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Zanthoxylum', 'Zanthoxylum procerum', 1, 2, 480) 
INSERT INTO Species(NonScientificName, ScientificName, fk_idSpeciesType, fk_Characteristic, fk_Period)
VALUES ('Zono', 'Bedotia tricolor', 2, 5, 481)