package com.TEC.Resources;

public class Strings {
    public static final String COSTA_RICA = "Costa Rica";
    public static final String USA = "United States";
    public static final String GERMANY = "Germany";
    public static final String NAME = "Name";
    public static final String COUNTRY_ID = "CountryId";
    public static final String STATE_ID = "StateId";
    public static final String CITY_ID = "CityId";
    public static final String COUNTRY = "Country";
    public static final String STATE = "State";
    public static final String CITY = "City";
    public static final String COUNTRIES = "Countries";
    public static final String STATES = "States";
    public static final String CITIES = "Cities";
    public static final String PERSON_ID = "PersonId";
    public static final String ID_NUMBER = "IdNumber";
    public static final String SURNAME = "Surname";
    public static final String LOCATION_ID = "LocationId";
    public static final String PHONE_NUMBER = "PhoneNumber";
    public static final String EMPLOYEE_ID = "EmployeeId";
    public static final String PARK_ID = "ParkId";
    public static final String PROFESSION_ID = "ProfessionId";
    public static final String ASSIGNED_AREA_ID = "AssignedAreaId";
    public static final String SPECIALITY_ID = "SpecialityId";
    public static final String RECEPTIONIST_ID = "ReceptionistId";
    public static final String ENTRANCE_NUMBER = "EntranceNumber";
    public static final String SECURITYGUARD_ID = "SecurityGuardId";
    public static final String ASSIGNED_AREA = "AssignedArea";
    public static final String RESEARCHER_ID = "ResearcherId";
    public static final String CONSERVATIONIST_ID = "ConservationistId";
    public static final String VEHICLE_ID = "VehicleId";
    public static final String DIPLOMA = "Diploma";
    public static final String SPECIALITY = "Speciality";
    public static final String FOUNDATION_DATE = "FoundationDate";
    public static final String COMMUNITY_ID = "CommunityId";
    public static final String NUMBER_OF_PARKS = "NumberOfParks";
    public static final String TOTAL_PROTECTED_AREA = "TotalProtectedArea";
    public static final String PROFESSION = "Profession";
    public static final String VISITOR_ID = "VisitorId";
    public static final String VISIT_ID = "VisitId";
    public static final String ACCOMMODATION_ID = "AccommodationId";
    public static final String START_DATE = "StartDate";
    public static final String END_DATE = "EndDate";
    public static final String CATEGORY = "Category";
    public static final String CAPACITY = "Capacity";
    public static final String EXCURSION_ID = "ExcursionId";
    public static final String PRICE = "Price";
    public static final String DESCRIPTION = "Description";
    public static final String DATE = "Date";
    public static final String HOUR = "Hour";
    public static final String TYPE = "Type";
    public static final String REGISTRATION_NUMBER = "RegistrationNumber";

    public static final String DASH = "-";
    public static final String SP_DOT = "\\.";
    public static final String AMPERSAND = "&";
    public static final String NEWLINE = "\n";
    public static final String DOT = ".";
    public static final String COMMA = ",";
    public static final String TD = "td";
    public static final String TR = "tr";
    public static final String TH = "th";
    public static final String EMPTY_STRING = "";
    public static final String SPACE = " ";
    public static final String WIKI_DIV_CLASS = "//div[@class='Rand-stage']";
    public static final String WIKI_TBL_CLASS1 = "//table[@class='wikitable sortable jquery-tablesorter']";
    public static final String WIKI_TBL_CLASS2 = "//table[@class='wikitable sortable plainrowheaders jquery-tablesorter']";
    public static final String WIKI_TBL_STYLE = "//table[@style='background:#ffffff']";
}
